---
title: "Parallel Worlds"
author: "Francesco Prem Solidoro, Michele Salvi"
format: pdf
editor: visual
---

```{r}
library(tidyverse)
library(paletteer)
library(ggthemes)
library(knitr)
library(psych)
library(readr)
library(ggpmisc)
#| echo: false
```

```{r}
#importing, merging and cleaning

IRAtweets1 <- read_csv("Data/IRAhandle_tweets_1.csv")
IRAtweets2 <- read_csv("Data/IRAhandle_tweets_2.csv")
IRAtweets3 <- read_csv("Data/IRAhandle_tweets_3.csv")
IRAtweets4 <- read_csv("Data/IRAhandle_tweets_4.csv")
IRAtweets5 <- read_csv("Data/IRAhandle_tweets_5.csv")
IRAtweets6 <- read_csv("Data/IRAhandle_tweets_6.csv")
IRAtweets7 <- read_csv("Data/IRAhandle_tweets_7.csv")
IRAtweets8 <- read_csv("Data/IRAhandle_tweets_8.csv")
IRAtweets9 <- read_csv("Data/IRAhandle_tweets_9.csv")
IRAtweets10 <- read_csv("Data/IRAhandle_tweets_10.csv")
IRAtweets11 <- read_csv("Data/IRAhandle_tweets_11.csv")
IRAtweets12 <- read_csv("Data/IRAhandle_tweets_12.csv")
IRAtweets13 <- read_csv("Data/IRAhandle_tweets_13.csv")

df_list <- list(IRAtweets1,IRAtweets2,IRAtweets3,IRAtweets4,IRAtweets5,IRAtweets6,IRAtweets7,IRAtweets8,IRAtweets9,IRAtweets10,IRAtweets11,IRAtweets12,IRAtweets13)

IRAtweets <- do.call("rbind", df_list)
IRAtweets <- subset(IRAtweets, select=c(-external_author_id,-harvested_date,-new_june_2018,-alt_external_id,-tweet_id,-article_url,-tco1_step1,-tco2_step1,-tco3_step1))

kable(head(IRAtweets))

#| echo: false
```

```{r}
IRAtweets <- IRAtweets[sample(nrow(IRAtweets), 100000),] #remove line for complete analysis

#descriptive stuff

mean_imp <- IRAtweets %>%
  select(c(author,updates,region,language)) %>% 
  group_by(author) %>%
  mutate(mean_Impressions = round(mean(updates),digits = 3)) %>%
  arrange(desc(mean_Impressions))

Lang_P <- IRAtweets %>% 
  group_by(language) %>%
  summarize(count = n())%>% 
  arrange(desc(count))%>%
  slice(1:6)%>%
  ungroup() %>%
  ggplot(aes(reorder(language, count),count/10000))+
  geom_bar(stat = "identity",fill = "darkblue")+
  coord_flip()+
  theme_bw()+
  labs(x = "Language", y = "Tweets (tens of thousands)", title = "Most Significant Languages")

Region_P <-  IRAtweets %>% 
  group_by(region) %>%
  summarize(count = n())%>% 
  arrange(desc(count))%>%
  slice(1:6)%>%
  ungroup() %>%
  ggplot(aes(reorder(region, count),count/10000))+
  geom_bar(stat = "identity", fill = "darkred")+
  coord_flip()+
  theme_bw()+
  labs(x = "Region", y = "Tweets (tens of thousands)", title = "Most Significant Regions")

Acctype_P <-  IRAtweets %>% 
  group_by(account_category) %>%
  summarize(count = n())%>% 
  arrange(desc(count))%>%
  ungroup() %>%
  ggplot(aes(reorder(account_category, count),count/10000))+
  geom_bar(stat = "identity", fill = "darkgreen")+
  coord_flip()+
  theme_bw()+
  labs(x = "Account Categories", y = "Tweets (tens of thousands)", title = "Tweet by Account types")

totimp_mean <- mean(mean_imp$mean_Impressions)

Meanimp_P <- mean_imp %>%
  group_by(region)%>%
  add_count(region)%>%
  ungroup() %>%
  mutate(rank = dense_rank(desc(n)))%>%
  filter(rank %in% 1:6)%>%
  ggplot(aes(mean_Impressions))+
  geom_histogram(aes(fill = region))+
  geom_vline(aes(xintercept=totimp_mean))+
  annotate("text", x=totimp_mean+3000, y=20000, label="Average ", angle = 90)+
  scale_fill_paletteer_d("nbapalettes::bucks_city2")+
  theme_bw()+
  labs(x = "Average impressions",y = "", title = "Average Tweet Impressions in significant regions") 


describe(IRAtweets$followers)
describe(IRAtweets$following)

mean(IRAtweets$retweet)
IRAtweets %>%
  group_by(account_category) %>%
  summarize(retweet_rate = mean(retweet)) %>%
  arrange(desc(retweet_rate))

Regionacctype_P <- IRAtweets %>%
  group_by(region)%>%
  add_count(region)%>%
  ungroup() %>%
  mutate(rank = dense_rank(desc(n)))%>%
  filter(rank %in% 1:2)%>%
  distinct(author, .keep_all = T)%>%
  group_by(account_category) %>%
  ggplot(aes(account_category))+
  geom_bar(fill = "#CE1141FF")+
  facet_wrap(vars(region))+
  scale_fill_paletteer_d("nbapalettes::bulls")+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90))+
  labs(x = "Account Categories",y = "Accounts", title = "Account categories in significant regions")

Regionacctype_P

#hypothertical time density plot

Timeseries_P <- IRAtweets %>% 
  mutate(timedates = as.Date(lubridate::parse_date_time(publish_date,"%m/%d/%Y %h:%M")))%>%
  group_by(timedates) %>%
  add_count(timedates)%>%
  filter(timedates > "2015-01-01" & timedates < "2018-01-01") %>% #basically no tweets before
  ggplot( aes(timedates,n))+
  geom_line(color = "#DB3EB1FF")+
  scale_x_date(date_labels = "%Y-%m-%d", date_breaks ="1 year" )+
  stat_peaks(geom = "point", span = 45, color = "#41B6E6FF", size = 2,ignore_threshold = 0.69) +
  stat_peaks(geom = "label", span = 45, color = "#41B6E6FF", angle = 0,
             hjust = -0.1, x.label.fmt = "%Y-%m-%d", ignore_threshold = 0.69)+
  labs(x = "Time",y = "Tweets", title = "Tweets over time")+
  theme_bw()

Lang_P
Region_P
Acctype_P
Meanimp_P
#Timeseries_P #WARNING, TAKES LOTS OF TIME TO PLOT















```

```{r}
#sentiment analysis


```
